# Generated by Django 4.1 on 2022-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=2)),
                ('symptoms', models.CharField(max_length=150)),
                ('medication', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'medical_cards',
            },
        ),
    ]
