# Generated by Django 4.1 on 2022-08-22 09:49

import django.core.validators
from django.db import migrations, models

import apps.users.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.users.services.upload_to),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,100}$', 'only letters min 2 max 100 char')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^0[9567]{1}\\d{8}$', 'Invalid phone number')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,100}$', 'only letters min 2 max 100 char')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])([^\\s]){8,50}$', ['Password must contain 1 number (0-9)', 'Password must 1 uppercase letters', 'Password must 1 lowercase letters', 'Password must1 non-alpha numeric number', 'Password is 8-50 characters with no space'])]),
        ),
    ]
