# Generated by Django 4.1 on 2022-08-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_card', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medical_cards.medicalcardmodel')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
