# Generated by Django 4.1 on 2022-08-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='patients',
            field=models.ManyToManyField(through='doctors.AppointmentModel', to='patients.patientmodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctormodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmodel'),
        ),
    ]
