# Generated by Django 4.1.1 on 2022-09-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctormodel',
            options={'ordering': ['id']},
        ),
    ]
